language: python

cache:
  - pip

python:
  - "3.6"

install:
  - pip install -U pip wheel
  - pip install cython
  - pip install autopep8 hacking==1.0.0

script:
  - flake8
  - flake8 --config=.flake8.cython
  - autopep8 -r . --global-config .pep8 --diff | tee check_autopep8
  - test ! -s check_autopep8

sudo: false
